name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm install
      
    - name: Criar .env
      run: |
        echo "PORT_REST=${{ secrets.PORT_REST }}" >> .env
        echo "PORT_GRAPHQL=${{ secrets.PORT_GRAPHQL }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env

    - name: Subir a API Rest 
      run: npm run start-rest &
    
    - name: Esperar as APIs estarem Funcionando
      run: sleep 8

    - name: Subir a API GraphQL
      run: npm run start-graphql &

    - name: Rodar testes unitários
      run: npm run test-unit

    - name: Rodar testes de controller
      run: npm run test-rest-controller

    - name: Rodar testes External de API Rest via HTTP
      run: npm run test-rest-external
    
    - name: Rodar testes de GraphQL
      run: npm run test-graphql